const places = {
  "MD":[["Moldova","Chișinău"],
  ["Moldova","Tiraspol"],
  ["Moldova","Bălți"],
  ["Moldova","Bender"],
  ["Moldova","Rîbnița"],
  ["Moldova","Ungheni"],
  ["Moldova","Cahul"],
  ["Moldova","Soroca"],
  ["Moldova","Orhei"],
  ["Moldova","Dubăsari"],
  ["Moldova","Comrat"],
  ["Moldova","Strășeni"],
  ["Moldova","Durlești"],
  ["Moldova","Ceadîr-Lunga"],
  ["Moldova","Căușeni"],
  ["Moldova","Codru"],
  ["Moldova","Edineț"],
  ["Moldova","Drochia"],
  ["Moldova","Ialoveni"],
  ["Moldova","Hîncești"]],
  "SK":[["Slovakia","Bratislava"],
  ["Slovakia","Trnava"],
  ["Slovakia","Trenčín"],
  ["Slovakia","Nitra"],
  ["Slovakia","Žilina"],
  ["Slovakia","Banská Bystrica"],
  ["Slovakia","Prešov"],
  ["Slovakia","Košice"]],
  "RO":[["Romania","Bucharest"],
  ["Romania","Cluj-Napoca"],
  ["Romania","Timișoara"],
  ["Romania","Iași"],
  ["Romania","Constanța"],
  ["Romania","Craiova"],
  ["Romania","Brașov"],
  ["Romania","Galați"],
  ["Romania","Ploiești"],
  ["Romania","Oradea"],
  ["Romania","Brăila"],
  ["Romania","Arad"],
  ["Romania","Pitești"],
  ["Romania","Sibiu"],
  ["Romania","Bacău"],
  ["Romania","Târgu Mureș"],
  ["Romania","Baia Mare"],
  ["Romania","Buzău"],
  ["Romania","Botoșani"],
  ["Romania","Satu Mare"],
  ["Romania","Râmnicu Vâlcea"],
  ["Romania","Drobeta-Turnu Severin"],
  ["Romania","Suceava"],
  ["Romania","Piatra Neamț"],
  ["Romania","Târgu Jiu"],
  ["Romania","Târgoviște"],
  ["Romania","Focșani"],
  ["Romania","Bistrița"],
  ["Romania","Tulcea"],
  ["Romania","Reșița"]],
  "SI":[["Slovenia","Ljubljana"],
  ["Slovenia","Maribor"],
  ["Slovenia","Kranj"],
  ["Slovenia","Celje"],
  ["Slovenia","Koper"],
  ["Slovenia","Velenje"],
  ["Slovenia","Novo Mesto"],
  ["Slovenia","Ptuj"],
  ["Slovenia","Kamnik"],
  ["Slovenia","Trbovlje"],
  ["Slovenia","Jesenice"],
  ["Slovenia","Domžale"],
  ["Slovenia","Nova Gorica"],
  ["Slovenia","Izola"],
  ["Slovenia","Škofja Loka"],
  ["Slovenia","Murska Sobota"],
  ["Slovenia","Logatec"],
  ["Slovenia","Postojna"],
  ["Slovenia","Vrhnika"],
  ["Slovenia","Slovenska Bistrica"]],
  "RS":[["Serbia","Belgrade"],
  ["Serbia","Novi Sad"],
  ["Serbia","Niš"],
  ["Serbia","Kragujevac"],
  ["Serbia","Leskovac"],
  ["Serbia","Subotica"],
  ["Serbia","Kruševac"],
  ["Serbia","Kraljevo"],
  ["Serbia","Pančevo"],
  ["Serbia","Zrenjanin"],
  ["Serbia","Šabac"],
  ["Serbia","Čačak"],
  ["Serbia","Smederevo"],
  ["Serbia","Novi Pazar"],
  ["Serbia","Valjevo"],
  ["Serbia","Sombor"],
  ["Serbia","Vranje"],
  ["Serbia","Sremska Mitrovica"],
  ["Serbia","Loznica"],
  ["Serbia","Užice"],
  ["Serbia","Požarevac"],
  ["Serbia","Jagodina"],
  ["Serbia","Stara Pazova"],
  ["Serbia","Zaječar"],
  ["Serbia","Kikinda"],
  ["Serbia","Pirot"]],
  "BG":[["Bulgaria","Sofia"],
  ["Bulgaria","Plovdiv"],
  ["Bulgaria","Varna"],
  ["Bulgaria","Burgas"],
  ["Bulgaria","Ruse"],
  ["Bulgaria","Stara Zagora"],
  ["Bulgaria","Pleven"],
  ["Bulgaria","Sliven"],
  ["Bulgaria","Dobrich"],
  ["Bulgaria","Shumen"],
  ["Bulgaria","Pernik"],
  ["Bulgaria","Haskovo"],
  ["Bulgaria","Yambol"],
  ["Bulgaria","Pazardzhik"],
  ["Bulgaria","Blagoevgrad"],
  ["Bulgaria","Veliko Tarnovo"],
  ["Bulgaria","Vratsa"],
  ["Bulgaria","Gabrovo"],
  ["Bulgaria","Asenovgrad"],
  ["Bulgaria","Vidin"],
  ["Bulgaria","Kazanlak"],
  ["Bulgaria","Kyustendil"],
  ["Bulgaria","Kardzhali"],
  ["Bulgaria","Montana"],
  ["Bulgaria","Dimitrovgrad"]],
  "HR":[["Croatia","Zagreb"],
  ["Croatia","Split"],
  ["Croatia","Rijeka"],
  ["Croatia","Osijek"],
  ["Croatia","Zadar"],
  ["Croatia","Velika Gorica"],
  ["Croatia","Pula"],
  ["Croatia","Slavonski Brod"],
  ["Croatia","Karlovac"],
  ["Croatia","Varaždin"],
  ["Croatia","Šibenik"],
  ["Croatia","Dubrovnik"],
  ["Croatia","Sisak"],
  ["Croatia","Kaštela"],
  ["Croatia","Samobor"],
  ["Croatia","Bjelovar"],
  ["Croatia","Vinkovci"],
  ["Croatia","Koprivnica"],
  ["Croatia","Čakovec"],
  ["Croatia","Solin"],
  ["Croatia","Zaprešić"],
  ["Croatia","Đakovo"],
  ["Croatia","Sinj"],
  ["Croatia","Vukovar"],
  ["Croatia","Požega"]],
  "EG":[["Egypt","Cairo"],
  ["Egypt","Alexandria"],
  ["Egypt","Gizeh"],
  ["Egypt","Shubra El-Kheima"],
  ["Egypt","Port Said"],
  ["Egypt","Suez"],
  ["Egypt","Luxor"],
  ["Egypt","al-Mansura"],
  ["Egypt","El-Mahalla El-Kubra"],
  ["Egypt","Tanta"],
  ["Egypt","Asyut"],
  ["Egypt","Ismailia"],
  ["Egypt","Fayyum"],
  ["Egypt","Zagazig"],
  ["Egypt","Aswan"],
  ["Egypt","Damietta"],
  ["Egypt","Damanhur"],
  ["Egypt","al-Minya"],
  ["Egypt","Beni Suef"],
  ["Egypt","Qena"],
  ["Egypt","Sohag"],
  ["Egypt","Hurghada"],
  ["Egypt","6th of October City"],
  ["Egypt","Shibin El Kom"],
  ["Egypt","Banha"],
  ["Egypt","Kafr el-Sheikh"],
  ["Egypt","Arish"],
  ["Egypt","Mallawi"],
  ["Egypt","10th of Ramadan City"],
  ["Egypt","Bilbais"],
  ["Egypt","Marsa Matruh"],
  ["Egypt","Idfu"],
  ["Egypt","Mit Ghamr"],
  ["Egypt","Al-Hamidiyya"],
  ["Egypt","Desouk"],
  ["Egypt","Qalyub"],
  ["Egypt","Abu Kabir"],
  ["Egypt","Kafr el-Dawwar"],
  ["Egypt","Girga"],
  ["Egypt","Akhmim"],
  ["Egypt","Matareya"]],
  "SA":[["Saudi Arabia","Riyadh"],
  ["Saudi Arabia","Jeddah"],
  ["Saudi Arabia","Mecca"],
  ["Saudi Arabia","Medina"],
  ["Saudi Arabia","Ad Dammām"],
  ["Saudi Arabia","Al Hufūf"],
  ["Saudi Arabia","Buraydah"],
  ["Saudi Arabia","Al Ḩillah"],
  ["Saudi Arabia","Aţ Ţā’if"],
  ["Saudi Arabia","Tabūk"],
  ["Saudi Arabia","Khamīs Mushayţ"],
  ["Saudi Arabia","Ḩā’il"],
  ["Saudi Arabia","Al Qaţīf"],
  ["Saudi Arabia","Al Mubarraz"],
  ["Saudi Arabia","Al Kharj"],
  ["Saudi Arabia","Najrān"],
  ["Saudi Arabia","Yanbu‘"],
  ["Saudi Arabia","Abhā"],
  ["Saudi Arabia","Arar"],
  ["Saudi Arabia","Jāzān"],
  ["Saudi Arabia","Sakākā"],
  ["Saudi Arabia","Al Bāḩah"]],
  "PLS":[["Poland","Warsaw"],
  ["Poland","Kraków"],
  ["Poland","Łódź"],
  ["Poland","Wrocław"],
  ["Poland","Poznań"],
  ["Poland","Gdańsk"],
  ["Poland","Szczecin"],
  ["Poland","Bydgoszcz"],
  ["Poland","Lublin"],
  ["Poland","Białystok"],
  ["Poland","Katowice"],
  ["Poland","Gdynia"],
  ["Poland","Częstochowa"],
  ["Poland","Radom"],
  ["Poland","Rzeszów"],
  ["Poland","Toruń"],
  ["Poland","Sosnowiec"],
  ["Poland","Kielce"],
  ["Poland","Gliwice"],
  ["Poland","Olsztyn"],
  ["Poland","Zabrze"],
  ["Poland","Bielsko-Biała"],
  ["Poland","Bytom"],
  ["Poland","Zielona Góra"],
  ["Poland","Rybnik"],
  ["Poland","Ruda Śląska"],
  ["Poland","Opole"],
  ["Poland","Tychy"],
  ["Poland","Gorzów Wielkopolski"],
  ["Poland","Elbląg"],
  ["Poland","Dąbrowa Górnicza"],
  ["Poland","Płock"],
  ["Poland","Wałbrzych"],
  ["Poland","Włocławek"],
  ["Poland","Tarnów"],
  ["Poland","Chorzów"],
  ["Poland","Koszalin"],
  ["Poland","Kalisz"],
  ["Poland","Legnica"],
  ["Poland","Grudziądz"],
  ["Poland","Jaworzno"],
  ["Poland","Słupsk"],
  ["Poland","Jastrzębie Zdrój"],
  ["Poland","Nowy Sącz"],
  ["Poland","Jelenia Góra"],
  ["Poland","Siedlce"],
  ["Poland","Mysłowice"],
  ["Poland","Konin"],
  ["Poland","Piła"],
  ["Poland","Piotrków Trybunalski"],
  ["Poland","Lubin"],
  ["Poland","Inowrocław"],
  ["Poland","Ostrów Wielkopolski"],
  ["Poland","Suwałki"],
  ["Poland","Stargard"],
  ["Poland","Gniezno"],
  ["Poland","Ostrowiec Świętokrzyski"],
  ["Poland","Siemianowice Śląskie"],
  ["Poland","Głogów"],
  ["Poland","Pabianice"],
  ["Poland","Leszno"],
  ["Poland","Żory"],
  ["Poland","Zamość"],
  ["Poland","Pruszków"],
  ["Poland","Łomża"],
  ["Poland","Ełk"],
  ["Poland","Tarnowskie Góry"],
  ["Poland","Tomaszów Mazowiecki"],
  ["Poland","Chełm"],
  ["Poland","Mielec"],
  ["Poland","Kędzierzyn-Koźle"],
  ["Poland","Przemyśl"],
  ["Poland","Stalowa Wola"],
  ["Poland","Tczew"],
  ["Poland","Biała Podlaska"],
  ["Poland","Bełchatów"],
  ["Poland","Świdnica"],
  ["Poland","Będzin"],
  ["Poland","Zgierz"],
  ["Poland","Piekary Śląskie"],
  ["Poland","Racibórz"],
  ["Poland","Legionowo"],
  ["Poland","Ostrołęka"]],
  "DES":[["Germany","Berlin"],
  ["Germany","Hamburg"],
  ["Germany","Munich"],
  ["Germany","Cologne"],
  ["Germany","Frankfurt am Main"],
  ["Germany","Stuttgart"],
  ["Germany","Düsseldorf"],
  ["Germany","Dortmund"],
  ["Germany","Essen"],
  ["Germany","Leipzig"],
  ["Germany","Bremen"],
  ["Germany","Dresden"],
  ["Germany","Hanover"],
  ["Germany","Nuremberg"],
  ["Germany","Duisburg"],
  ["Germany","Bochum"],
  ["Germany","Wuppertal"],
  ["Germany","Bielefeld"],
  ["Germany","Bonn"],
  ["Germany","Münster"],
  ["Germany","Karlsruhe"],
  ["Germany","Mannheim"],
  ["Germany","Augsburg"],
  ["Germany","Wiesbaden"],
  ["Germany","Gelsenkirchen"],
  ["Germany","Mönchengladbach"],
  ["Germany","Braunschweig"],
  ["Germany","Chemnitz"],
  ["Germany","Kiel"],
  ["Germany","Aachen"],
  ["Germany","Halle"],
  ["Germany","Magdeburg"],
  ["Germany","Freiburg im Breisgau"],
  ["Germany","Krefeld"],
  ["Germany","Lübeck"],
  ["Germany","Oberhausen"],
  ["Germany","Erfurt"],
  ["Germany","Mainz"],
  ["Germany","Rostock"],
  ["Germany","Kassel"],
  ["Germany","Hagen"],
  ["Germany","Hamm"],
  ["Germany","Saarbrücken"],
  ["Germany","Mülheim an der Ruhr"],
  ["Germany","Potsdam"],
  ["Germany","Ludwigshafen am Rhein"],
  ["Germany","Oldenburg"],
  ["Germany","Leverkusen"],
  ["Germany","Osnabrück"],
  ["Germany","Solingen"],
  ["Germany","Heidelberg"],
  ["Germany","Herne"],
  ["Germany","Neuss"],
  ["Germany","Darmstadt"],
  ["Germany","Paderborn"],
  ["Germany","Regensburg"],
  ["Germany","Ingolstadt"],
  ["Germany","Würzburg"],
  ["Germany","Fürth"],
  ["Germany","Wolfsburg"],
  ["Germany","Offenbach am Main"],
  ["Germany","Ulm"],
  ["Germany","Heilbronn"],
  ["Germany","Pforzheim"],
  ["Germany","Göttingen"],
  ["Germany","Bottrop"],
  ["Germany","Trier"],
  ["Germany","Recklinghausen"],
  ["Germany","Reutlingen"],
  ["Germany","Bremerhaven"],
  ["Germany","Koblenz"],
  ["Germany","Bergisch Gladbach"],
  ["Germany","Jena"],
  ["Germany","Remscheid"],
  ["Germany","Erlangen"],
  ["Germany","Moers"],
  ["Germany","Siegen"],
  ["Germany","Hildesheim"],
  ["Germany","Salzgitter"],
  ["Germany","Silesian"],
  ["Germany","Masovian"]]
}